export const INTEREST_GROUPS={
Technical:[
  "Analytics",
  "AR/VR",
  "Blockchain Development",
  "Competitive Programming",
  "Consultancy",
  "CTF",
  "Data Science",
  "Drones",
  "DSA",
  "Event management",
  "Finance",
  "Game Development",
  "Graphic Design",
  "Information Security",
  "Maths",
  "ML",
  "Mobile Development",
  "Motion Design",
  "Probability Statistics",
  "Product management",
  "Quant",
  "Quantum Computing",
  "Robotics",
  "Stock market",
  "UI/UX Design",
  "Web Development",
],

Artistic:[
  "Audio",
  "casting",
  "Choreography",
  "Content Writing",
  "Costume Design",
  "Dance",
 "Directing",
  "DJ",
  "Fashion modelling",
  "Film making",
  "Music",
  "Musical Instruments",
  "Music production",
  "Photography",
  "Podcasting",
  "RJ",
  "Script writing",
  "Video editing",
  "Videography",
],

Core:[
  "Aerodynamics",
  "Automotives",
  "CAD-CAM",
  "Electronics",
  "Formula one",
  "Hardware Engineering",
  "Mechanical",
  "Physics and Astronomy",
],

Miscellaneous:[
  "Business administration",
  "Chess",
  "Communication",
  "Debating",
  "Field work",
  "Leadership",
  "Marketing",
  "Mentorship",	
  "Mountaineering",
  "Politics",
  "Range Rovering",
  "Sanskrit",
  "Skating",
  "Social media",
  "Soft skills",
  "Team management",
  "Trekking",
  "Wellness",
]

}